// Auto-generated by `cargo xtask openapi-gen`. Do not edit manually.
use utoipa::OpenApi;

use crate::router::delete::delete_data::__path_delete_data;
use crate::router::fairing::guard_hash::__path_renew_hash_token;
use crate::router::fairing::guard_timestamp::__path_renew_timestamp_token;
use crate::router::get::get_album_index::__path_get_album_index_status;
use crate::router::get::get_config::__path_export_config_handler;
use crate::router::get::get_config::__path_get_config_handler;
use crate::router::get::get_data::__path_get_data;
use crate::router::get::get_data::__path_get_rows;
use crate::router::get::get_data::__path_get_scroll_bar;
use crate::router::get::get_export::__path_get_export;
use crate::router::get::get_fs_completion::__path_get_fs_completion;
use crate::router::get::get_img::__path_compressed_file;
use crate::router::get::get_img::__path_imported_file;
use crate::router::get::get_list::__path_get_albums;
use crate::router::get::get_list::__path_get_tags;
use crate::router::get::get_prefetch::__path_prefetch;
use crate::router::post::album_index::__path_cancel_album_index_handler;
use crate::router::post::album_index::__path_index_album_handler;
use crate::router::post::album_index::__path_index_image_handler;
use crate::router::post::authenticate::__path_authenticate;
use crate::router::post::create_dir_album::__path_create_dir_album;
use crate::router::post::create_share::__path_create_share;
use crate::router::post::import_config::__path_import_config_handler;
use crate::router::post::post_upload::__path_upload;
use crate::router::put::assign_album::__path_assign_album;
use crate::router::put::edit_album::__path_set_album_cover;
use crate::router::put::edit_album::__path_set_album_title;
use crate::router::put::edit_config::__path_update_config_handler;
use crate::router::put::edit_config::__path_update_password_handler;
use crate::router::put::edit_description::__path_set_user_defined_description;
use crate::router::put::edit_flags::__path_edit_flags;
use crate::router::put::edit_share::__path_delete_share;
use crate::router::put::edit_share::__path_edit_share;
use crate::router::put::edit_tag::__path_edit_tag;
use crate::router::put::regenerate_thumbnail::__path_regenerate_thumbnail_with_frame;
use crate::router::put::reindex::__path_reindex;
use crate::router::put::rotate_image::__path_rotate_image;

#[derive(OpenApi)]
#[openapi(
    paths(
        // ── GET routes
        get_album_index_status,
        export_config_handler,
        get_config_handler,
        get_data,
        get_rows,
        get_scroll_bar,
        get_export,
        get_fs_completion,
        compressed_file,
        imported_file,
        get_albums,
        get_tags,
        prefetch,

        // ── POST routes
        cancel_album_index_handler,
        index_album_handler,
        index_image_handler,
        authenticate,
        create_dir_album,
        create_share,
        import_config_handler,
        upload,

        // ── PUT routes
        assign_album,
        set_album_cover,
        set_album_title,
        update_config_handler,
        update_password_handler,
        set_user_defined_description,
        edit_flags,
        delete_share,
        edit_share,
        edit_tag,
        regenerate_thumbnail_with_frame,
        reindex,
        rotate_image,

        // ── DELETE routes
        delete_data,

        // ── FAIRING routes
        renew_hash_token,
        renew_timestamp_token,
    ),
)]
pub struct ApiDoc;

#[must_use]
pub fn generate_json() -> String {
    ApiDoc::openapi()
        .to_json()
        .expect("OpenAPI serialization failed")
}
